### ISSUE TITLE
Start all steps from the raw data

### ISSUE THREAD

**Issue by mbahmani** [janvanrijn/openml-pimp#9]
Hi,

As I understood, the result Notebook can reproduce the following items Based on fanova data:

a. Marginal contribution per dataset.
b. important hyperparameter per dataset. 
c. Prior experiments for three classifiers.

But I want to start all the steps from raw data! Can you please guide me how to execute 
the code form the first step to the end?

I think I should call openmlpimp!

Also, I have a problem to install pyrfr for running fanova code.

Thanks in advance.

**Comment by mbahmani** [comment]
Hi again @janvanrijn 
I know you are extremely busy but that would be a great help for me if you just give me some tips for reproducing the paper result from row data?
I am looking forward to your reply.
Thank you.

**Comment by janvanrijn** [comment]
Thanks for your interest! I was on a small holiday, but should be able to assist a bit. In order to install `pyrfr` you should probably install `swig`. This can be done in Miniconda. 

I have some sample code on the `openml-python` package that helps generating these experiments: 
https://github.com/openml/openml-python/blob/develop/examples/40_paper/2018_kdd_rijn_example.py

Note that this code is a simplified version of the paper:
* it takes all data directly from OpenML (so we have 2 years more data then when I did the original experiments, this should not influence the results)
* it does not take into account log-scales for hyperparameters (this influences the results, but it should be fairly easy to include them for the relevant hyperparameters)

Hope this helps! Feel free to let me know how far you got.

**Comment by mbahmani** [comment]
@janvanrijn Thanks for your reply! that helps me a lot.
